apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-new
  namespace: flux-system
spec:
  interval: 30s
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-new
  path: ./clusters/dev
