apiVersion: v1
kind: Service
metadata:
  name: service-py
  namespace: apps
  labels:
    app: service-py
spec:
  selector:
    app: service-py
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
